OPCDA:
 ProgId: opcserversim.Instance.1
 Nodes: ["localhost"]
 Tags: ["StringValue", "DateTimeValue", "DateValue", "TimeValue", "WordValue"]
Kafka:
 Brokers: ["192.168.1.9:29092"]
 Topic: helll
 Partition: 0